// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXFskQVnTM5twbIlmC0RaxjgE_HBNaFg0',
    appId: '1:651253520510:web:79b012d2edcde2d93c202f',
    messagingSenderId: '651253520510',
    projectId: 'tiktok-202502',
    authDomain: 'tiktok-202502.firebaseapp.com',
    storageBucket: 'tiktok-202502.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxWu0l1pkgkx-IMkl4ezylTfLA8-B4S9w',
    appId: '1:651253520510:android:6c1d6ee72c4e92fb3c202f',
    messagingSenderId: '651253520510',
    projectId: 'tiktok-202502',
    storageBucket: 'tiktok-202502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa26tGRgt8eCnUIn8fuXUx8J937rmGAds',
    appId: '1:651253520510:ios:21c1156eedb10b413c202f',
    messagingSenderId: '651253520510',
    projectId: 'tiktok-202502',
    storageBucket: 'tiktok-202502.firebasestorage.app',
    iosBundleId: 'com.example.tictokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa26tGRgt8eCnUIn8fuXUx8J937rmGAds',
    appId: '1:651253520510:ios:21c1156eedb10b413c202f',
    messagingSenderId: '651253520510',
    projectId: 'tiktok-202502',
    storageBucket: 'tiktok-202502.firebasestorage.app',
    iosBundleId: 'com.example.tictokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXFskQVnTM5twbIlmC0RaxjgE_HBNaFg0',
    appId: '1:651253520510:web:f6640d72230839293c202f',
    messagingSenderId: '651253520510',
    projectId: 'tiktok-202502',
    authDomain: 'tiktok-202502.firebaseapp.com',
    storageBucket: 'tiktok-202502.firebasestorage.app',
  );

}